# Generated by Django 4.0.4 on 2022-06-17 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakery', '0002_alter_bakery_logo_alter_bakery_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_records', to='bakery.bakery')),
            ],
        ),
        migrations.CreateModel(
            name='HumiditySensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity_records', to='bakery.bakery')),
            ],
        ),
    ]
